import { Navbar } from '@/layouts'
import './globals.css'
import type { Metadata } from 'next'
import { Inter as Sans, Italiana as Serif, Anton as Mono, Inter } from 'next/font/google'

const sans = Sans({ subsets: ['latin'] })
const mono = Mono({ subsets : ['latin'], variable : '--font-anton', display : 'swap', weight : ['400']})
const serif = Serif({ weight : ['400'], variable : '--font-italiana', subsets : ['latin'], display : 'swap'})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${sans.className} ${serif.variable} ${mono.variable}`}>
      <body >
        <Navbar />
        {children}</body>
    </html>
  )
}
